############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

#[[main]]
#name = "About"
#url = "/about"
#weight = 2

[[main]]
name = "Call For Papers"
url = "/about"
weight = 2

[[main]]
name = "Organizers"
url = "/authors"
weight = 3

[[main]]
name = "Schedule"
url = "/schedule"
weight = 4

#[[main]]
#weight = 4
#name = "Pages"

#[[main]]
#parent = "Pages"
#name = "Blog"
#url = "/blog"

# footer menu
#[[footer]]
#name = "About"
#url = "/about"
#weight = 1

#[[footer]]
#name = "Elements"
#url = "/elements"
#weight = 2

#[[footer]]
#name = "Privacy Policy"
#url = "/privacy-policy"
#weight = 3
